version: "3.8"
services:
  # first container
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports: 
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass

  # second container
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 18081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb

# this is how we store the data
volumes:
  data: {}

# networks to share between mongodb and mongo-express; so they can talk to each other
networks:  
  default:
    name: mongodb_network

  